build

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -5,92 +5,145 @@ on:
       - feat-dast
 
 jobs:        
-  SAST:
-    runs-on: ubuntu-latest
-    steps:
-
-    - name: Set up JDK 17
-      uses: actions/setup-java@v2
-      with:
-        java-version: '17'
-        distribution: 'adopt'
-
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Hola Mundo
-      run: | 
-        echo 'Hola mundo!'
-    
-    - name: Build
-      run: | 
-        chmod 777 gradlew
-        ./gradlew build
-
-    - name: Validando existencia de proyecto en SonarCloud
-      id: validateProjectOnSonar
-      run: |
-        #pwd
-        #ls -R
-        set +e
-        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=curso-devsecops-usach-test' -d 'visibility=public'
-        if [ $? -ne 0 ]; then
-          echo "Proyecto ya existe en Sonarcloud"
-          echo "::set-output name=proyectoExiste::1"
-        else
-          echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
-          
-          echo "Se establece rama main como rama por defecto"
-          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
-        fi
-        set -e
-
-    - name: Validando tipo de proyecto
-      id: tipoProyecto
-      if: steps.validateProjectOnSonar.outputs.proyectoExiste == '1'
-      run: |
-        pwd
-        ls -R
-        if [ -f "build.gradle" ]
-        then
-          echo "Proyecto Java"
-          if grep -q 'id "org.sonarqube" version "3.3"' build.gradle
-          then
-            echo "El plugin de SonarCloud ya está presente en build.gradle"
-          else
-            sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
-            echo "El plugin de SonarCloud no estaba presente y se ha sido añadido a build.gradle"
-            cat build.gradle
-          fi
-
-        else
-          echo "Tipo de proyecto desconocido"
-        fi
-
-
-    - name: Enable execution gradlew
-      run: | 
-        chmod 777 gradlew
-    
-    - name: Run SonarQube analysis
-      run: |
-        ./gradlew sonarqube \
-        -Dsonar.projectKey=${{ github.event.repository.name }} \
-        -Dsonar.organization=curso-devsecops-usach-test \
-        -Dsonar.host.url=https://sonarcloud.io \
-        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
-        -Dsonar.branch.name=
+#  SAST:
+#    runs-on: ubuntu-latest
+#    steps:
+#
+#    - name: Set up JDK 17
+#      uses: actions/setup-java@v2
+#      with:
+#        java-version: '17'
+#        distribution: 'adopt'
+#
+#    - name: Checkout code
+#      uses: actions/checkout@v2
+#
+#    - name: Hola Mundo
+#      run: | 
+#        echo 'Hola mundo!'
+#    
+#    - name: Build
+#      run: | 
+#        chmod 777 gradlew
+#        ./gradlew build
+#
+#    - name: Validando existencia de proyecto en SonarCloud
+#      id: validateProjectOnSonar
+#      run: |
+#        #pwd
+#        #ls -R
+#        set +e
+#        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=curso-devsecops-usach-test' -d 'visibility=public'
+#        if [ $? -ne 0 ]; then
+#          echo "Proyecto ya existe en Sonarcloud"
+#          echo "::set-output name=proyectoExiste::1"
+#        else
+#          echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
+#          
+#          echo "Se establece rama main como rama por defecto"
+#          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
+#        fi
+#        set -e
+#
+#    - name: Validando tipo de proyecto
+#      id: tipoProyecto
+#      if: steps.validateProjectOnSonar.outputs.proyectoExiste == '1'
+#      run: |
+#        pwd
+#        ls -R
+#        if [ -f "build.gradle" ]
+#        then
+#          echo "Proyecto Java"
+#          if grep -q 'id "org.sonarqube" version "3.3"' build.gradle
+#          then
+#            echo "El plugin de SonarCloud ya está presente en build.gradle"
+#          else
+#            sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
+#            echo "El plugin de SonarCloud no estaba presente y se ha sido añadido a build.gradle"
+#            cat build.gradle
+#          fi
+#
+#        else
+#          echo "Tipo de proyecto desconocido"
+#        fi
+#
+#
+#    - name: Enable execution gradlew
+#      run: | 
+#        chmod 777 gradlew
+#    
+#    - name: Run SonarQube analysis
+#      run: |
+#        ./gradlew sonarqube \
+#        -Dsonar.projectKey=${{ github.event.repository.name }} \
+#        -Dsonar.organization=curso-devsecops-usach-test \
+#        -Dsonar.host.url=https://sonarcloud.io \
+#        -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
+#        -Dsonar.branch.name=
 
 
 #--------------------- SCA -------------------------------------------
       
-  SCA:
-    needs: SAST
-    runs-on: ubuntu-latest
+#  SCA:
+#    needs: SAST
+#    runs-on: ubuntu-latest
+#    steps:
+#    
+#    - name: Checkout code
+#      uses: actions/checkout@v2      
+#
+#    - name: Build
+#      id: build
+#      run: |
+#        #pwd
+#        #ls -R
+#        if [ -f "build.gradle" ]
+#        then
+#          echo "Utiliza build.gradle, proyecto Java"
+#          echo "Se habilita permiso de ejecución de archivo gradlew"
+#          chmod 777 gradlew
+#          ./gradlew build
+#          ls -R
+#        else
+#          echo "Otro tipo de proyecto"
+#        fi
+#    
+#    - name: Dependency Check
+#      uses: dependency-check/Dependency-Check_Action@1.1.0
+#      env:
+#        JAVA_HOME: /opt/jdk
+#      id: Depcheck
+#      with:
+#        project: '${{ github.event.repository.name }}'
+#        path: '.'
+#        format: 'HTML'
+#        out: 'reports'
+#        args: >
+#          --failOnCVSS 7
+#          --enableRetired
+#
+#    - name: Upload Test result
+#      uses: actions/upload-artifact@master
+#      with:
+#        name: Depcheck report
+#        path: ${{github.workspace}}/reports
+#
+#    - name: Upload Test result
+#      uses: actions/upload-artifact@master
+#      with:
+#        name: JAR
+#        path: ${{github.workspace}}/build/libs/spring-petclinic-2.6.0.jar
+
+
+#-------------------- Docker Build Image ----------------------------
+
+  DockerBuild:
+#    needs: SCA
+    runs-on: self-hosted
     steps:
     
     - name: Checkout code
-      uses: actions/checkout@v2      
+      uses: actions/checkout@v2
 
     - name: Build
       id: build
@@ -103,59 +156,23 @@ jobs:
           echo "Se habilita permiso de ejecución de archivo gradlew"
           chmod 777 gradlew
           ./gradlew build
+          cp ${{github.workspace}}/build/libs/spring-petclinic-2.6.0.jar ${{github.workspace}}/pet-clinic/pet-clinic
           ls -R
         else
           echo "Otro tipo de proyecto"
         fi
     
-    - name: Dependency Check
-      uses: dependency-check/Dependency-Check_Action@1.1.0
-      env:
-        JAVA_HOME: /opt/jdk
-      id: Depcheck
-      with:
-        project: '${{ github.event.repository.name }}'
-        path: '.'
-        format: 'HTML'
-        out: 'reports'
-        args: >
-          --failOnCVSS 7
-          --enableRetired
-
-    - name: Upload Test result
-      uses: actions/upload-artifact@master
-      with:
-        name: Depcheck report
-        path: ${{github.workspace}}/reports
-
-    - name: Upload Test result
-      uses: actions/upload-artifact@master
-      with:
-        name: JAR
-        path: ${{github.workspace}}/build/libs/spring-petclinic-2.6.0.jar
-
-
-#-------------------- Docker Build Image ----------------------------
-
-  DockerBuild:
-    needs: SCA
-    runs-on: self-hosted
-    steps:
-    
-    - name: Checkout code
-      uses: actions/checkout@v2
-
     - name: Docker Login
       uses: docker/login-action@v3.0.0
       with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Download JAR
-      uses: actions/download-artifact@master
-      with:
-        name: JAR
-        path: ${{github.workspace}}
+#    - name: Download JAR
+#      uses: actions/download-artifact@master
+#      with:
+#        name: JAR
+#        path: ${{github.workspace}}
     
     - name: Build Docker
       run: |
