Build & Push Docker Image

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -5,102 +5,123 @@ on:
       - feat-devsecops
 
 jobs:
-  SAST:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-      
-      - name: Validando existencia de proyecto en SonarCloud
-        id: validateProjectOnSonar
-        run: |
-          #pwd
-          #ls -R
-          set +e
-          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=devsecopsusach' -d 'visibility=public'
-          if [ $? -ne 0 ]; then
-            echo "Proyecto ya existe en Sonarcloud"
-            echo "::set-output name=proyectoExiste::1"
-          else
-            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
-            
-            echo "Se establece rama main como rama por defecto"
-            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
-          fi
-          set -e
-      
-      - name: Validando tipo de proyecto
-        run: |
-          if [ -f "build.gradle" ]; then
-            echo "El proyecto es de tipo Gradle"
-            if grep -q 'id "org.sonarqube" version "3.3"' build.gradle; then
-              echo "El plugin de SonarQube ya está configurado en build.gradle"
-            else
-              sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
-              echo "Plugin de SonarQube agregado a build.gradle"
-              cat build.gradle
-            fi
-          else
-            echo "No se encontró un archivo de construcción válido (build.gradle o pom.xml)"
-            exit 1
-          fi
-      
-      - name: Ejecutando Sonarcloud
-        run: |
-          chmod 777 gradlew
-          ./gradlew sonarqube \
-            -Dsonar.projectKey=${{ github.event.repository.name }}-curso-seguridad \
-            -Dsonar.organization=curso-seguridad \
-            -Dsonar.host.url=https://sonarcloud.io \
-            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
-            -Dsonar.branch.name=main
+  #SAST:
+  #  runs-on: ubuntu-latest
+  #  steps:
+  #    - name: Checkout code
+  #      uses: actions/checkout@v3
+  #    
+  #    - name: Validando existencia de proyecto en SonarCloud
+  #      id: validateProjectOnSonar
+  #      run: |
+  #        #pwd
+  #        #ls -R
+  #        set +e
+  #        curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=devsecopsusach' -d 'visibility=public'
+  #        if [ $? -ne 0 ]; then
+  #          echo "Proyecto ya existe en Sonarcloud"
+  #          echo "::set-output name=proyectoExiste::1"
+  #        else
+  #          echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
+  #          
+  #          echo "Se establece rama main como rama por defecto"
+  #          curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
+  #        fi
+  #        set -e
+  #    
+  #    - name: Validando tipo de proyecto
+  #      run: |
+  #        if [ -f "build.gradle" ]; then
+  #          echo "El proyecto es de tipo Gradle"
+  #          if grep -q 'id "org.sonarqube" version "3.3"' build.gradle; then
+  #            echo "El plugin de SonarQube ya está configurado en build.gradle"
+  #          else
+  #            sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
+  #            echo "Plugin de SonarQube agregado a build.gradle"
+  #            cat build.gradle
+  #          fi
+  #        else
+  #          echo "No se encontró un archivo de construcción válido (build.gradle o pom.xml)"
+  #          exit 1
+  #        fi
+  #    
+  #    - name: Ejecutando Sonarcloud
+  #      run: |
+  #        chmod 777 gradlew
+  #        ./gradlew sonarqube \
+  #          -Dsonar.projectKey=${{ github.event.repository.name }}-curso-seguridad \
+  #          -Dsonar.organization=curso-seguridad \
+  #          -Dsonar.host.url=https://sonarcloud.io \
+  #          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
+  #          -Dsonar.branch.name=main
 
-      - name: Validando resultado de SonarCloud
-        run: | 
+  #    - name: Validando resultado de SonarCloud
+  #      run: | 
 
-          issueValidate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}-curso-seguridad&facets=severities' | jq '.facets[0].values[1].count')
-          echo "Cantidad de issues bloqueantes: $issueValidate"
-          if [ "$issueValidate" -gt 0 ]; then
-            echo "Se encontraron issues bloqueantes. Se quiebra el pipeline."
-            #exit 1
-          else
-            echo "No se encontraron issues bloqueantes. Pipeline Continua."
-          fi
+  #        issueValidate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=${{ github.event.repository.name }}-curso-seguridad&facets=severities' | jq '.facets[0].values[1].count')
+  #        echo "Cantidad de issues bloqueantes: $issueValidate"
+  #        if [ "$issueValidate" -gt 0 ]; then
+  #          echo "Se encontraron issues bloqueantes. Se quiebra el pipeline."
+  #          #exit 1
+  #        else
+  #          echo "No se encontraron issues bloqueantes. Pipeline Continua."
+  #        fi
   
-  SCA:
-    needs: SAST
+  #SCA:
+  #  needs: SAST
+  #  runs-on: ubuntu-latest
+  #  steps:
+  #    - name: Checkout code
+  #      uses: actions/checkout@v3
+
+  #    - name: Set up JDK 17
+  #      uses: actions/setup-java@v2
+  #      with:
+  #        java-version: '17'
+  #        distribution: 'adopt'
+
+  #    - name: build with Gradle
+  #      run: | 
+  #        chmod 777 gradlew
+  #        ./gradlew build
+
+  #    - name: Run OWASP Dependency-Check
+  #      uses: dependency-check/Dependency-Check_Action@1.1.0
+  #      env:
+  #        JAVA_HOME: /opt/jdk
+  #      with:
+  #        project: '${{ github.event.repository.name }}'
+  #        path: '.'
+  #        format: 'HTML'
+  #        out: 'reports'
+  #        args: >
+  #          --failOnCVSS 7
+  #          --enableRetired
+  #    
+  #    - name: Upload Test results
+  #      uses: actions/upload-artifact@master
+  #      if: always()
+  #      with:
+  #         name: Depcheck report
+  #         path: ${{github.workspace}}/reports
+
+  DockerBuild:
+    #needs: SCA
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
-        with:
-          java-version: '17'
-          distribution: 'adopt'
+      - name: Build Docker Image
+        run: |
+          docker build --tag petclinic:latest .
 
-      - name: build with Gradle
+      - name: Login to DockerHub
+        uses: docker/login-action@v3.0.0
+        with:
+          username: ${{ secrets.DOCKER_USER }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Push to DockerHub
         run: | 
-          chmod 777 gradlew
-          ./gradlew build
-
-      - name: Run OWASP Dependency-Check
-        uses: dependency-check/Dependency-Check_Action@1.1.0
-        env:
-          JAVA_HOME: /opt/jdk
-        with:
-          project: '${{ github.event.repository.name }}'
-          path: '.'
-          format: 'HTML'
-          out: 'reports'
-          args: >
-            --failOnCVSS 7
-            --enableRetired
-      
-      - name: Upload Test results
-        uses: actions/upload-artifact@master
-        if: always()
-        with:
-           name: Depcheck report
-           path: ${{github.workspace}}/reports
+          docker push ${{ secrets.DOCKER_USER }}/petclinic:latest
