validacion, configuracion y ejecucion SAST

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -16,11 +16,11 @@ jobs:
         run: |
           curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}-curso-seguridad' -d 'organization=curso-seguridad' -d 'project=${{ github.event.repository.name }}-curso-seguridad' -d 'visibility=private'
           
-          if [ $? -eq 0 ]; then
+          if [ $? -ne 0 ]; then
+            echo "El proyecto ya existe en SonarCloud o hubo un error al crearlo"
+          else
             echo "Proyecto creado exitosamente en SonarCloud"
             curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}-curso-seguridad'
-          else
-            echo "El proyecto ya existe en SonarCloud o hubo un error al crearlo"
           fi
       
       - name: Validando tipo de proyecto
